name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests (test_local)
      run: make test_local

    - name: Run tests (test_package)
      run: make test_package

    - name: Run full make
      run: make

      
